image: jekyll/jekyll

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - gem install json kramdown
  - pip3 install pyyaml

pages:
  stage: deploy
  script:
    - make --always-make site
  artifacts:
    paths:
    - public
  only:
    - master

