image: git.embl.de:4567/grp-bio-it-workshops/building-websites-with-jekyll-and-github-or-gitlab

variables:
  LC_ALL: "C.UTF-8"
  MAKEFLAGS: "-j 8"

pages:
  stage: deploy
  script:
    - make lesson-check
    - make lesson-check-all
    - make site
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
